# Uncomment the next line to define a global platform for your project
# platform :ios, '13.2'

target 'MComics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImageSwiftUI', '~> 0.9.0'

  target 'MComicsTests' do
    inherit! :search_paths
    pod 'KIF'
    pod 'Nimble'
    pod 'Quick'
    pod 'Swifter'
  end
end
